### ISSUE TITLE
Error: You must supply options.input to rollup

### ISSUE THREAD

**Issue by canadaduane** [ParamagicDev/snowpack-plugin-rollup-bundle#20]
I'm a little confused by the above error message. I don't see an "options.input" anywhere in the options to `snowpack-plugin-rollup-bundle`.

Here is my configuration:
```
    [
      "snowpack-plugin-rollup-bundle",
      {
        // equivalent to inputOptions.input from Rollup
        entrypoints: "index.js",

        extendConfig: (config) => {
          // https://rollupjs.org/guide/en/#outputoptions-object
          // config.outputOptions = { ... }

          // https://rollupjs.org/guide/en/#inputoptions-object
          // config.inputOptions = { ... }

          return config;
        },
      },
    ],
```

Maybe it means that `config.inputOptions` is required?

**Comment by ParamagicDev** [comment]
@canadaduane so I think I should make it a little more clear, but your entrypoint should be where you build with Snowpack build.


So if your `out` directory is set to `build` you should have an entrypoint of:

`entrypoints: "build/index.js"`

Let me know how that works for you!

**Comment by canadaduane** [comment]
I see! That makes sense, thank you.
