### ISSUE TITLE
Resolve absolute path `/_dist_` assets

### ISSUE THREAD

**Issue by canadaduane** [ParamagicDev/snowpack-plugin-rollup-bundle#21]
I'm using a (self-authored) snowpack plugin that [re-writes relative-path CSS](https://github.com/canadaduane/snowpack-plugin-relative-css-urls) `url()` URLs into absolute path URLs. So for example, this CSS in `src/ui/Button/Button.svelte`:

```
.image {
  background-image: url(./checkmark.png);
}
```

becomes

```
.image {
  background-image: url(/_dist_/ui/Button/checkmark.png);
}
```

when written to the snowpack build directory.

When bundling this in rollup, it looks like rollup can't resolve absolute `/_dist/...` paths:

```
yarn build
yarn run v1.21.1
$ snowpack build
[snowpack] ! building source…
[snowpack] ✔ build complete [0.09s]
[snowpack] installing dependencies...
[snowpack] ✔ install complete! [0.22s]
[snowpack]
  ⦿ web_modules/           size       gzip       brotli
    └─ svelte/internal.js  7.94 KB    2.29 KB    2.01 KB


[snowpack] ! verifying build...
[snowpack] ✔ verification complete
[snowpack] ! writing build to disk...
[snowpack] ✔ build complete [0.09s]
Unresolved URL `/_dist_/styles/x.svg` in `--x-icon: url(/_dist_/styles/x.svg)`
Unresolved URL `/_dist_/ui/Button/checkmark.png` in `background-image:url(/_dist_/ui/Button/checkmark.png)`
Unresolved URL `/_dist_/ui/Button/logo.svg` in `background-image:url(/_dist_/ui/Button/logo.svg)`
mv: rename dist to /var/folders/bl/vmhly6rn6kbd7hphg614m4b80000gn/T/_source_/dist: No such file or directory
[snowpack] ▶ Build Complete!


✨  Done in 4.29s.
```

I'm wondering if this is a thing `snowpack-plugin-rollup-bundle` should be able to do, or should my plugin be re-writing the URLs within CSS differently? If the latter, I can think of two possible ways to go:

1. Write different output for snowpack build mode than dev mode
2. Write relative URLs instead of absolute

**Comment by ParamagicDev** [comment]
So the plugin as its currently written has no concept of absolute paths.

A `/_dist/` would literally refer to `/_dist` on your computer and not `blah/my-projects/build-directory/_dist` which is what im assuming youre trying to do.

**Comment by canadaduane** [comment]
Ok. Could it be written to replace absolute paths with the snowpack mount directories in mind?

I'm re-considering whether my second option "Write relative URLs instead of absolute" is even an option (because in dev mode, css is transformed to proxy.js files that can't have 'relative' CSS urls). Let me see if option no. 1 (different output for build mode vs dev mode) works.

**Comment by canadaduane** [comment]
Thinking about this some more... I think we may need to have rollup resolve the absolute URLs somehow. Here's why:

CSS normally allows relative images. It does so through a "baseURI" property--a read-only property that is set when CSS files are loaded by the browser. This allows a CSS file's internal `url()` references to refer to assets relative to the CSS file, NOT the path of the current page (i.e. the HTML file).

When snowpack adds `*.css.proxy.js` files in place of `*.css` files, it injects a `style` tag with the CSS corresponding to the `.css` file into the page. Everything in these proxy CSS files works EXCEPT relative `url()` paths, because there is no way to set the dynamically created style tag's `baseURI`.

Without this additional information (the baseURI to resolve the `url()` references from) there is no "relative path" on the browser side that will consistently work--it would depend on the page the user is visiting whether the CSS works (BAD). So the URLs inside `url()` references must be absolute.

That leaves only one option that I can see: we need the final bundling step (rollup, in this case) to understand what to do with these absolute URLs.

See also:

- https://stackoverflow.com/questions/3812375/specifying-base-url-for-css
- https://developer.mozilla.org/en-US/docs/Web/API/Node/baseURI
- https://developer.mozilla.org/en-US/docs/Web/HTML/Element/base
- https://developer.mozilla.org/en-US/docs/Web/CSS/url()

**Comment by canadaduane** [comment]
Created a relevant discussion here: https://github.com/pikapkg/snowpack/discussions/1327

**Comment by ParamagicDev** [comment]
Ahhh this makes sense. So the way this plugin works right now is it simply augments the process started by Snowpack. Whatever Snowpack generates for production, it just bundles it up. I'll read more into it. Right now this plugin is meant for SSR so it extracts CSS rather than injecting it into the head of files. I'll have to peruse through this and think on it a little more. Thanks for creating the issue and discussion!

**Comment by ParamagicDev** [comment]
@canadaduane does this issue happen when you use `snowpack build` without `snowpack-plugin-rollup-bundle` ?

**Comment by canadaduane** [comment]
I'm not actually sure. I don't have the plugin stack working far enough that snowpack-plugin-rollup-bundle works all the way through to the end (with or without my URL munging inside CSS files).

If I don't use the `snowpack-plugin-relative-css-urls`, and try `snowpack-plugin-rollup-bundle`, currently I get a bunch of bundled JS but without the public directory (index.html, other assets) that should go with it.

**Comment by dishuostec** [comment]
@canadaduane 
I have meet same question. Currently I overwrited plugin `rollup-plugin-styles` used inside this plugin and add a custom resolver.

https://github.com/ParamagicDev/snowpack-plugin-rollup-bundle/blob/ddd20dc8ec28269388bc29007b4d15fbfc56770a/src/options.js#L6
https://github.com/ParamagicDev/snowpack-plugin-rollup-bundle/blob/ddd20dc8ec28269388bc29007b4d15fbfc56770a/src/options.js#L14-L19
You can try like this
```javascript
// snowpack.config.js
const path = require('path');
const styles = require('rollup-plugin-styles');

const buildDirectory = path.resolve(process.cwd, build);

const plugins = [
    // ...
    [
        "snowpack-plugin-rollup-bundle",
        {
            // ...
            extendConfig: (config) => {

                config.inputOptions.plugins.splice(1, 1, styles({
                    mode: ["extract"],
                    autoModules: (id) => id.includes(".module.css"),
                    minimize: true,
                    sourceMap: true,
                    url: {
                        publicPath: `../assets`, // path write back to css file
                        assetDir: 'assets', // path where copy asset to disk
                        hash: '[name]-[hash][extname]', // asset filename template
                        resolve: async (input, base) => {
                            const file = buildDirectory + input;
                            return {
                                from: path.relative(base, file),
                                source: await fs.readFileSync(file),
                            };
                        },
                    },
                }));

                return config;
            }
        }
    ]
]

module.exports = {
    plugins: plugins
}
```
