### ISSUE TITLE
Input sourcemaps should be loaded

### ISSUE THREAD

**Issue by angryziber** [ParamagicDev/snowpack-plugin-rollup-bundle#27]
Please consider using this by default:
https://www.npmjs.com/package/rollup-plugin-sourcemaps

Current sourcemaps relate to input files, but they themselves were generated from other source files (TypeScript/Svelte/etc), which are not visible in final source map.

**Comment by angryziber** [comment]
Currently, it is already possible to load input sourcemaps like this:
```
    ['snowpack-plugin-rollup-bundle', {
      ...
      extendConfig: config => {
        config.inputOptions.plugins.push(require('rollup-plugin-sourcemaps')())
        return config
      }
    }]
```

but it should be the default

**Comment by ParamagicDev** [comment]
Absolutely! Ill be honest, sourcemaps have been a gray spot I hadnt even thought to look at. Id be more than happy to integrate this into a `v0.3.4` for you!
