### ISSUE TITLE
OS agnostic file operations

### ISSUE THREAD

**Issue by Havegum** [ParamagicDev/snowpack-plugin-rollup-bundle#28]
Commands like `rm -rf ` are not available in windows, which causes this plugin to fail.

If taking on an additional dependency is acceptable, [fs-extra](https://github.com/jprichardson/node-fs-extra) is a possible solution as far as I can tell. It has all the necessary commands used in [index.js](https://github.com/ParamagicDev/snowpack-plugin-rollup-bundle/blob/master/src/index.js):

```diff
- import fs from "fs";
+ import fs from "fs-extra";

  /* ... */

- shellRun(`rm -rf ${TMP_DEBUG_DIRECTORY} && mkdir -p ${TMP_DEBUG_DIRECTORY}`);
- shellRun(`mv ${buildDirectory} ${TMP_DEBUG_DIRECTORY}`);
- shellRun(`mv ${TMP_BUILD_DIRECTORY} ${buildDirectory}`);
+ await fs.remove(TMP_DEBUG_DIRECTORY);
+ await fs.mkdirp(TMP_DEBUG_DIRECTORY);
+ await fs.move(buildDirectory, TMP_DEBUG_DIRECTORY, { overwrite: true });
+ await fs.move(TMP_BUILD_DIRECTORY, buildDirectory, { overwrite: true });

  if (pluginOptions.preserveSourceFiles === true) {
    const buildDebugDir = path.join(buildDirectory, "_source_");
-   shellRun(`mv ${TMP_DEBUG_DIRECTORY}/ ${buildDebugDir}`);
+   await fs.move(TMP_DEBUG_DIRECTORY + "/", buildDebugDir, { overwrite: true })
  }

**Comment by ParamagicDev** [comment]
Awesome! Thank you, I don't have a windows installation to test on. If you have WSL you could use that for now if you would like. I'm working on a v1 release and I'll be sure to include this change.
